#!/bin/bash
clear
echo "Hello $1 ! Let's play..."


credits(){
  clear
  echo "Credits..."
  echo "Developed by Ronnie King"
  echo "Thank you for playing the Scratchwerk Game!"
  main
}

exit_game(){
  clear
  echo "Thanks for playing!"
}

fight(){
  echo "Prepare to fight!"
  echo "The enemies suddenly rush you all at once!"
  echo "You threw 50 punches and kicks!!"
  ran_num=$(( RANDOM % 100 ))
  echo "The enemy threw $ran_num punches and kicks"
  if [[ $ran_num -gt 50 ]]; then
    lose_fight
  else
    win_fight
  fi

}

#Lose Fight
lose_fight(){
 echo "You didn't throw enough punches and you were defeated.  Try again..."
 sleep 5
 clear
 main
}

#Win Fight
win_fight(){
  echo "You are victorious!!"
  echo -n "Type Yes to play again or No to exit and Press Enter : "
  read next_action
  if [[ $next_action == "Yes" ]]; then
    main
  else
    exit_game
  fi
}


#Start game
start_game(){
  clear
  echo "Oh no! You're surrounded by enemies."
  echo "There are five of them, and they're all armed"
  echo "If you fight them, you'll have a chance of winning"
  echo -n "Type fight or run and press Enter : "
  read action
  if [[ $action == "fight" ]]; then
    fight
  elif [[ $action == "run" ]]; then
    echo "Running from it will not save you.  You lost!"
    echo -n "Would you like to play again? Type Yes or No and press Enter : "
    read play_again
    if [[ $play_again == "Yes" ]]; then
      start_game
    else
      exit_game
    fi
  else
    echo "Invalid choice!"
    sleep 5
    exit_game
  fi
}


main(){
  echo "1. Start"
  echo "2. Credits"
  echo "3. Exit"
  echo -n "Type the number of your option and press Enter : "
  read answer
  if [[ $answer -eq 1 ]]; then
     start_game
  elif [[ $answer -eq 2 ]]; then
     credits
  elif [[ $answer -eq 3 ]]; then
    exit_game
  else
    echo "Invalid option"
  fi
}

main
